
//silver_chain_scope_start
//mannaged by silver chain
#include "../../imports/imports.mac.h"
//silver_chain_scope_end

typedef struct private_CerradoSync_ProcessStruct CerradoSync_Process;

typedef struct private_CerradoSyncStruct CerradoSyn;

typedef struct private_CerradoSync_Arguments_struct CerradoSync_ArgumentsCallback;

typedef struct private_CerradoSync_Argument_struct CerradoSync_ArgumentCallback;

typedef struct private_CerradoSync_CallbackProcess_struct CerradoSync_CallbackProcess;

typedef struct private_CerradoSync_MemorySharedContent_struct CerradoSync_MemorySharedContent;

typedef struct private_CerradoSync_MemoryShared_struct CerradoSync_MemoryShared;

typedef struct private_CerradoSync_TrafficPointersList_struct CerradoSync_TrafficPointersList;

typedef struct private_CerradoSync_TrafficPointerObject_struct CerradoSync_TrafficPointerObject;

typedef struct private_CerradoSync_TrafficMemory_struct CerradoSync_TrafficMemory;


